### ISSUE TITLE
Can’ｔ[Passing the Updated Policy Set to Authzforce]

### ISSUE THREAD

**Issue by hsakamoto123** [FIWARE/tutorials.Administrating-XACML#9]
Execution of the following request resulted in "Internal Server Error".
What should be done?
```
Then re-create it using a POST request as shown:
1️⃣7️⃣ Request
$ curl -X POST \
>   http://localhost:3005/v1/applications/tutorial-dckr-site-0000-xpresswebapp/roles/security-role-0000-0000-000000000000/permissions/alrmbell-ring-24hr-xaml-000000000000 \
>   -H 'Content-Type: application/json' \
>   -H 'X-Auth-token: aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa'
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Internal Server Error</pre>
</body>
</html>
```
The result of "docker ps" and the log of the container at this time are as follows.
```
$ docker ps -a
CONTAINER ID   IMAGE                                       COMMAND                  CREATED          STATUS                    PORTS                                                                                            NAMES
d1b0ecf9510e   fiware/tutorials.context-provider           "/nodejs/bin/node ./…"   31 minutes ago   Up 31 minutes (healthy)   0.0.0.0:3000-3001->3000-3001/tcp, :::3000-3001->3000-3001/tcp                                    fiware-tutorial
37e54e4efa09   fiware/iotagent-ul:1.24.0-distroless        "/nodejs/bin/node ./…"   31 minutes ago   Up 31 minutes (healthy)   0.0.0.0:4041->4041/tcp, :::4041->4041/tcp, 0.0.0.0:7896->7896/tcp, :::7896->7896/tcp, 4061/tcp   fiware-iot-agent
8f629852fc6d   fiware/pep-proxy:8.3.0-distroless           "/nodejs/bin/node ./…"   31 minutes ago   Up 31 minutes (healthy)   0.0.0.0:1027->1027/tcp, :::1027->1027/tcp                                                        fiware-orion-proxy
4ed8b8171c53   fiware/orion:3.0.0                          "/usr/bin/contextBro…"   31 minutes ago   Up 31 minutes (healthy)   0.0.0.0:1026->1026/tcp, :::1026->1026/tcp                                                        fiware-orion
b3cf7c6d40d1   fiware/idm:8.3.1-distroless                 "/nodejs/bin/node ./…"   31 minutes ago   Up 31 minutes (healthy)   3000/tcp, 0.0.0.0:3005->3005/tcp, :::3005->3005/tcp                                              fiware-keyrock
6bcb79b02107   mysql:8.0                                   "docker-entrypoint.s…"   31 minutes ago   Up 31 minutes             0.0.0.0:3306->3306/tcp, :::3306->3306/tcp, 33060/tcp                                             db-mysql
9bd1b923fb69   fiware/authzforce-ce-server:release-8.1.0   "catalina.sh run"        31 minutes ago   Up 31 minutes (healthy)   0.0.0.0:8080->8080/tcp, :::8080->8080/tcp                                                        fiware-authzforce
f86de15460a2   mongo:4.4                                   "docker-entrypoint.s…"   31 minutes ago   Up 31 minutes (healthy)   0.0.0.0:27017->27017/tcp, :::27017->27017/tcp                                                    db-mongo


# tail -f b3cf7c6d40d12c48d53366aa25765a5a3711de2f16e2563f14056b1ed01c9257/b3cf7c6d40d12c48d53366aa25765a5a3711de2f16e2563f14056b1ed01c9257-json.log
{"log":"2023-01-06T11:08:13.147Z idm:api-authenticate  --\u003e validate_token\n","stream":"stderr","time":"2023-01-06T11:08:13.147530456Z"}
{"log":"2023-01-06T11:08:13.153Z idm:api-applications --\u003e load_application\n","stream":"stderr","time":"2023-01-06T11:08:13.153160042Z"}
{"log":"2023-01-06T11:08:13.154Z idm:api-check_permissions_controller --\u003e check_request\n","stream":"stderr","time":"2023-01-06T11:08:13.154680718Z"}
{"log":"2023-01-06T11:08:13.154Z idm:api-check_permissions_controller --\u003e owned_permissions\n","stream":"stderr","time":"2023-01-06T11:08:13.154746731Z"}
{"log":"2023-01-06T11:08:13.158Z idm:api-roles --\u003e load_role\n","stream":"stderr","time":"2023-01-06T11:08:13.160416884Z"}
{"log":"2023-01-06T11:08:13.159Z idm:api-permissions --\u003e load_permission\n","stream":"stderr","time":"2023-01-06T11:08:13.160439525Z"}
{"log":"2023-01-06T11:08:13.161Z idm:api-role_permission_assignments --\u003e create\n","stream":"stderr","time":"2023-01-06T11:08:13.165745235Z"}
{"log":"TypeError: models.role_permission.findOrCreate(...).spread is not a function\n","stream":"stderr","time":"2023-01-06T11:08:13.165770074Z"}
{"log":"    at exports.create (/opt/fiware-idm/controllers/api/role_permission_assignments.js:80:8)\n","stream":"stderr","time":"2023-01-06T11:08:13.165773481Z"}
{"log":"    at Layer.handle [as handle_request] (/opt/fiware-idm/node_modules/express/lib/router/layer.js:95:5)\n","stream":"stderr","time":"2023-01-06T11:08:13.165775458Z"}
{"log":"    at next (/opt/fiware-idm/node_modules/express/lib/router/route.js:144:13)\n","stream":"stderr","time":"2023-01-06T11:08:13.165777292Z"}
{"log":"    at Route.dispatch (/opt/fiware-idm/node_modules/express/lib/router/route.js:114:3)\n","stream":"stderr","time":"2023-01-06T11:08:13.165779134Z"}
{"log":"    at Layer.handle [as handle_request] (/opt/fiware-idm/node_modules/express/lib/router/layer.js:95:5)\n","stream":"stderr","time":"2023-01-06T11:08:13.165780934Z"}
{"log":"    at /opt/fiware-idm/node_modules/express/lib/router/index.js:284:15\n","stream":"stderr","time":"2023-01-06T11:08:13.165782784Z"}
{"log":"    at param (/opt/fiware-idm/node_modules/express/lib/router/index.js:365:14)\n","stream":"stderr","time":"2023-01-06T11:08:13.165784542Z"}
{"log":"    at paramCallback (/opt/fiware-idm/node_modules/express/lib/router/index.js:412:21)\n","stream":"stderr","time":"2023-01-06T11:08:13.165786303Z"}
{"log":"    at /opt/fiware-idm/controllers/api/permissions.js:31:9\n","stream":"stderr","time":"2023-01-06T11:08:13.165788097Z"}
{"log":"    at runMicrotasks (\u003canonymous\u003e)\n","stream":"stderr","time":"2023-01-06T11:08:13.165789905Z"}
{"log":"    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n","stream":"stderr","time":"2023-01-06T11:08:13.165791801Z"}
```

**Comment by jason-fox** [comment]
This is a Keyrock bug caused by the upgrade to Sequelize 6. I have raised an issue over there. @apozohue10 will need to fix the  code base.

**Comment by jason-fox** [comment]
I have recreated a new docker image including the bug fix.

```console
docker pull fiware/idm:8.3.1 
docker pull fiware/idm:8.3.1-distroless
```
